import type { Metadata } from "next";
import { Quicksand, Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/modules/Footer";
import Header from "@/modules/Header";
import ConsultForm from "@/modules/ConsultForm";
import ScrollUp from "@/components/ScrollUp";
import SocialMedia from "@/components/SocialMedia";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} ${inter.variable} antialiased`}
      >
        <section>
          <Header />
        </section>
        {children}
        <section id="contact">
          <ConsultForm />
        </section>
        <section id="ubication">
          <Footer />
        </section>
        <ScrollUp />
        <SocialMedia />
      </body>
    </html>
  );
}
